name: Create Issue on PR Merge with UI-changes Label

on:
  pull_request:
    types: [opened]

jobs:
  create_issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Debug Labels
        run: |
          echo "Labels on the PR: ${{ toJson(github.event.pull_request.labels) }}"

      - name: Check for specific label
        id: check_label
        run: |
          echo "Checking for the 'UI-changes' label..."
          if contains(github.event.issue.labels.*.name, 'UI-changes') then
            echo "Label 'UI-changes' found."
            echo "::set-output name=label_found::true"
          else
            echo "Label 'UI-changes' not found. Exiting. Labels are  ${{ toJson(github.event.pull_request.labels) }}"
            echo "::set-output name=label_found::false"
            exit 0
          fi
