name: Create Issue on PR Merge with UI-changes Label
run-name: ${{ toJson(github.event.pull_request.labels.name) }} is testing out GitHub Actions 🚀
on:
  pull_request:

jobs:
  create_issue:
    runs-on: self-hosted
    steps:
      - name: Create Issue
        run: |
          echo "Labels on the PR: ${{ toJson(github.event.pull_request.labels) }}"

      - name: Check for specific label
        run: |
          echo "Checking for the 'UI-changes' label..."
          if contains(github.event.pull_request.labels.name, 'UI-changes'); then
            echo "Label 'UI-changes' found."
            echo "::set-output name=label_found::true"
          else
            echo "Label 'UI-changes' not found. Exiting. Labels are  ${{ toJson(github.event.pull_request.labels) }}"
            echo "::set-output name=label_found::false"
            exit 0
          fi
