name: Create Issue on PR
on:
  push:
    branches:
      - master

jobs:
  create-issue:
    runs-on: self-hosted
    if: ${{github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'UI-changes')}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Issue for UI-changes
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: 'Tests for ${{ github.event.pull_request.labels.*.name }}'
          body: ${{contains(github.event.pull_request.labels.*.name, 'UI-changes')}}
          labels: e2e , test
      - name: Log GitHub event payload
        run: echo "${{github.event.pull_request.merged}}  ,  ${{github.event.pull_request.labels.*.name}}"
