name: Create Issue on PR

on:
  pull_request:
    types: [opened]

jobs:
  create-issue:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Issue
        id: create_issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'New Pull Request Created: ${{ github.event.pull_request.title }}'
          content-filepath: '.github/ISSUE_TEMPLATE/pull_request_created.md'
          labels: |
            pull request
            automated issue
