name: Create Issue on PR

on:
  pull_request:
    types: [closed]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR Details
        id: extract_pr_details
        run: |
          echo "::set-output name=title::Issue created due to merge PR: ${{ github.event.pull_request.title }}"
          echo "::set-output name=body::"
          echo "### Pull Request Details"
          echo "**Title:** ${{ github.event.pull_request.title }}"
          echo "**Description:** ${{ github.event.pull_request.body }}"
          echo "**Files Changed:**"

      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = '${{ steps.extract_pr_details.outputs.title }}';
            const body = '${{ steps.extract_pr_details.outputs.body }}';

            const issue = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['e2e', 'test'] // Add any labels you want here
            });
            console.log(`Created issue: ${issue.data.html_url}`);
