name: Create Issue on PR

on:
  pull_request:
    types: [opened]

jobs:
  create-issue:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = `New Pull Request Created: ${context.payload.pull_request.title}`;
            const body = `
            ## Pull Request Created

            A new pull request has been created.

            - **PR Title**: ${context.payload.pull_request.title}
            - **PR Link**: ${context.payload.pull_request.html_url}
            - **Author**: ${context.payload.pull_request.user.login}

            Please review the pull request and provide feedback.

            ---
            This issue was created automatically by a GitHub Action.
            `;

            const labels = ['pull request', 'automated issue'];

            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: labels
            });
