name: Create Issue on PR

on:
  pull_request:
    types: [closed]

jobs:
  create-issue:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Issue for UI-changes
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: 'Tests for ${{ github.event.pull_request.title }}'
          body: '#${{github.event.pull_request.number}}'
          labels: e2e , test
